#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_REVISION 0
#define VERSION_STRING_PRODUCT "1.0.0"
#define VERSION_STRING_FILE "1.0.0"
#define VERSION_DATE "0"
#define VERSION_TIME "0"
